<a href="https://colab.research.google.com/github/msussman42/CQE/blob/main/stack_and_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
a=np.array([[1,5,10]])
b=np.array([[2,4,11]])
atran=a.transpose()
btran=b.transpose()
print(a)
print(b)
print(atran)
print(btran)
Y=np.vstack((atran,btran))
print(Y)
YT=np.vstack((atran,btran)).T
print(YT)
n=10
for i in range(n):
  print(i)

[[ 1  5 10]]
[[ 2  4 11]]
[[ 1]
 [ 5]
 [10]]
[[ 2]
 [ 4]
 [11]]
[[ 1]
 [ 5]
 [10]
 [ 2]
 [ 4]
 [11]]
[[ 1  5 10  2  4 11]]
0
1
2
3
4
5
6
7
8
9
